Clustering: AGLP
Dataset: DS2
Indir: C:\ACCADIL\SRC\DIE-LINK-BENCHMARK\Datasets\SIMILARITIES\LislejourdainV1_BMP\DS2
Outdir: C:\ACCADIL\SRC\DIE-LINK-BENCHMARK\Datasets\CLUSTERING\LislejourdainV1_BMP\DS2
Treasure: LislejourdainV1_BMP
