Clustering: AGLP
Dataset: DS8
Indir: C:\ACCADIL\SRC\DIE-LINK-BENCHMARK\Datasets\SIMILARITIES\LislejourdainV1_BMP\DS8
Outdir: C:\ACCADIL\SRC\DIE-LINK-BENCHMARK\Datasets\CLUSTERING\LislejourdainV1_BMP\DS8
Treasure: LislejourdainV1_BMP
