Dataset: DS8
Distance: CORNET
Filtering: true
Matching:
  Algo: SIFT
  Params:
    RoMa-Threshold: 0.9
    XFeat-TopK: 5000
PATH_PROJECT: C:\ACCADIL\SRC\DIE-LINK-BENCHMARK
SIMILARITIES: Datasets\SIMILARITIES
Treasure: IJ_DS8
algo_matching: SIFT
